/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package mesos;

public class ExecutorArgs {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ExecutorArgs(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ExecutorArgs obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mesosJNI.delete_ExecutorArgs(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ExecutorArgs() {
    this(mesosJNI.new_ExecutorArgs__SWIG_0(), true);
  }

  public ExecutorArgs(String _slaveId, String _host, String _frameworkId, String _frameworkName, byte[] _data) {
    this(mesosJNI.new_ExecutorArgs__SWIG_1(_slaveId, _host, _frameworkId, _frameworkName, _data), true);
  }

  public void setSlaveId(String value) {
    mesosJNI.ExecutorArgs_slaveId_set(swigCPtr, this, value);
  }

  public String getSlaveId() {
    return mesosJNI.ExecutorArgs_slaveId_get(swigCPtr, this);
  }

  public void setHost(String value) {
    mesosJNI.ExecutorArgs_host_set(swigCPtr, this, value);
  }

  public String getHost() {
    return mesosJNI.ExecutorArgs_host_get(swigCPtr, this);
  }

  public void setFrameworkId(String value) {
    mesosJNI.ExecutorArgs_frameworkId_set(swigCPtr, this, value);
  }

  public String getFrameworkId() {
    return mesosJNI.ExecutorArgs_frameworkId_get(swigCPtr, this);
  }

  public void setFrameworkName(String value) {
    mesosJNI.ExecutorArgs_frameworkName_set(swigCPtr, this, value);
  }

  public String getFrameworkName() {
    return mesosJNI.ExecutorArgs_frameworkName_get(swigCPtr, this);
  }

  public void setData(byte[] value) {
    mesosJNI.ExecutorArgs_data_set(swigCPtr, this, value);
  }

  public byte[] getData() { 
    return mesosJNI.ExecutorArgs_data_get(swigCPtr, this); 
  }

}
