/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package mesos;

public class ExecutorDriver {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ExecutorDriver(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ExecutorDriver obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mesosJNI.delete_ExecutorDriver(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public int start() {
    return mesosJNI.ExecutorDriver_start(swigCPtr, this);
  }

  public int stop() {
    return mesosJNI.ExecutorDriver_stop(swigCPtr, this);
  }

  public int join() {
    return mesosJNI.ExecutorDriver_join(swigCPtr, this);
  }

  public int run() {
    return mesosJNI.ExecutorDriver_run(swigCPtr, this);
  }

  public int sendStatusUpdate(TaskStatus status) {
    return mesosJNI.ExecutorDriver_sendStatusUpdate(swigCPtr, this, TaskStatus.getCPtr(status), status);
  }

  public int sendFrameworkMessage(FrameworkMessage message) {
    return mesosJNI.ExecutorDriver_sendFrameworkMessage(swigCPtr, this, FrameworkMessage.getCPtr(message), message);
  }

  public ExecutorDriver() {
    this(mesosJNI.new_ExecutorDriver(), true);
  }

}
