/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package mesos;

public class Executor {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Executor(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Executor obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mesosJNI.delete_Executor(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    mesosJNI.Executor_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    mesosJNI.Executor_change_ownership(this, swigCPtr, true);
  }

  public void init(ExecutorDriver d, ExecutorArgs args) {
    if (getClass() == Executor.class) mesosJNI.Executor_init(swigCPtr, this, ExecutorDriver.getCPtr(d), d, ExecutorArgs.getCPtr(args), args); else mesosJNI.Executor_initSwigExplicitExecutor(swigCPtr, this, ExecutorDriver.getCPtr(d), d, ExecutorArgs.getCPtr(args), args);
  }

  public void launchTask(ExecutorDriver d, TaskDescription task) {
    if (getClass() == Executor.class) mesosJNI.Executor_launchTask(swigCPtr, this, ExecutorDriver.getCPtr(d), d, TaskDescription.getCPtr(task), task); else mesosJNI.Executor_launchTaskSwigExplicitExecutor(swigCPtr, this, ExecutorDriver.getCPtr(d), d, TaskDescription.getCPtr(task), task);
  }

  public void killTask(ExecutorDriver d, int taskId) {
    if (getClass() == Executor.class) mesosJNI.Executor_killTask(swigCPtr, this, ExecutorDriver.getCPtr(d), d, taskId); else mesosJNI.Executor_killTaskSwigExplicitExecutor(swigCPtr, this, ExecutorDriver.getCPtr(d), d, taskId);
  }

  public void frameworkMessage(ExecutorDriver d, FrameworkMessage message) {
    if (getClass() == Executor.class) mesosJNI.Executor_frameworkMessage(swigCPtr, this, ExecutorDriver.getCPtr(d), d, FrameworkMessage.getCPtr(message), message); else mesosJNI.Executor_frameworkMessageSwigExplicitExecutor(swigCPtr, this, ExecutorDriver.getCPtr(d), d, FrameworkMessage.getCPtr(message), message);
  }

  public void shutdown(ExecutorDriver d) {
    if (getClass() == Executor.class) mesosJNI.Executor_shutdown(swigCPtr, this, ExecutorDriver.getCPtr(d), d); else mesosJNI.Executor_shutdownSwigExplicitExecutor(swigCPtr, this, ExecutorDriver.getCPtr(d), d);
  }

  public void error(ExecutorDriver d, int code, String message) {
    if (getClass() == Executor.class) mesosJNI.Executor_error(swigCPtr, this, ExecutorDriver.getCPtr(d), d, code, message); else mesosJNI.Executor_errorSwigExplicitExecutor(swigCPtr, this, ExecutorDriver.getCPtr(d), d, code, message);
  }

  public Executor() {
    this(mesosJNI.new_Executor(), true);
    mesosJNI.Executor_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

}
