/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package mesos;

public class FrameworkMessage {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected FrameworkMessage(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FrameworkMessage obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mesosJNI.delete_FrameworkMessage(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public FrameworkMessage() {
    this(mesosJNI.new_FrameworkMessage__SWIG_0(), true);
  }

  public FrameworkMessage(String _slaveId, int _taskId, byte[] _data) {
    this(mesosJNI.new_FrameworkMessage__SWIG_1(_slaveId, _taskId, _data), true);
  }

  public void setSlaveId(String value) {
    mesosJNI.FrameworkMessage_slaveId_set(swigCPtr, this, value);
  }

  public String getSlaveId() {
    return mesosJNI.FrameworkMessage_slaveId_get(swigCPtr, this);
  }

  public void setTaskId(int value) {
    mesosJNI.FrameworkMessage_taskId_set(swigCPtr, this, value);
  }

  public int getTaskId() {
    return mesosJNI.FrameworkMessage_taskId_get(swigCPtr, this);
  }

  public void setData(byte[] value) {
    mesosJNI.FrameworkMessage_data_set(swigCPtr, this, value);
  }

  public byte[] getData() { 
    return mesosJNI.FrameworkMessage_data_get(swigCPtr, this); 
  }

}
