/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package mesos;

public class SchedulerDriver {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected SchedulerDriver(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SchedulerDriver obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mesosJNI.delete_SchedulerDriver(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public int start() {
    return mesosJNI.SchedulerDriver_start(swigCPtr, this);
  }

  public int stop() {
    return mesosJNI.SchedulerDriver_stop(swigCPtr, this);
  }

  public int join() {
    return mesosJNI.SchedulerDriver_join(swigCPtr, this);
  }

  public int run() {
    return mesosJNI.SchedulerDriver_run(swigCPtr, this);
  }

  public int sendFrameworkMessage(FrameworkMessage message) {
    return mesosJNI.SchedulerDriver_sendFrameworkMessage(swigCPtr, this, FrameworkMessage.getCPtr(message), message);
  }

  public int killTask(int tid) {
    return mesosJNI.SchedulerDriver_killTask(swigCPtr, this, tid);
  }

  public int replyToOffer(String oid, java.util.List<TaskDescription> task, java.util.Map<String, String> params) {
    return mesosJNI.SchedulerDriver_replyToOffer(swigCPtr, this, oid, task, params);
  }

  public int reviveOffers() {
    return mesosJNI.SchedulerDriver_reviveOffers(swigCPtr, this);
  }

  public int sendHints(java.util.Map<String, String> hints) {
    return mesosJNI.SchedulerDriver_sendHints(swigCPtr, this, hints);
  }

  public SchedulerDriver() {
    this(mesosJNI.new_SchedulerDriver(), true);
  }

}
