/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package mesos;

public class SlaveOffer {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected SlaveOffer(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SlaveOffer obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mesosJNI.delete_SlaveOffer(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SlaveOffer() {
    this(mesosJNI.new_SlaveOffer__SWIG_0(), true);
  }

  public SlaveOffer(String _slaveId, String _host, java.util.Map<String, String> _params) {
    this(mesosJNI.new_SlaveOffer__SWIG_1(_slaveId, _host, _params), true);
  }

  public void setSlaveId(String value) {
    mesosJNI.SlaveOffer_slaveId_set(swigCPtr, this, value);
  }

  public String getSlaveId() {
    return mesosJNI.SlaveOffer_slaveId_get(swigCPtr, this);
  }

  public void setHost(String value) {
    mesosJNI.SlaveOffer_host_set(swigCPtr, this, value);
  }

  public String getHost() {
    return mesosJNI.SlaveOffer_host_get(swigCPtr, this);
  }

  public void setParams(java.util.Map<String, String> value) {
    mesosJNI.SlaveOffer_params_set(swigCPtr, this, value);
  }

  public java.util.Map<String, String> getParams() {
    return mesosJNI.SlaveOffer_params_get(swigCPtr, this);
  }

}
