/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package mesos;

public class TaskDescription {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected TaskDescription(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TaskDescription obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mesosJNI.delete_TaskDescription(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public TaskDescription() {
    this(mesosJNI.new_TaskDescription__SWIG_0(), true);
  }

  public TaskDescription(int _taskId, String _slaveId, String _name, java.util.Map<String, String> _params, byte[] _arg) {
    this(mesosJNI.new_TaskDescription__SWIG_1(_taskId, _slaveId, _name, _params, _arg), true);
  }

  public void setTaskId(int value) {
    mesosJNI.TaskDescription_taskId_set(swigCPtr, this, value);
  }

  public int getTaskId() {
    return mesosJNI.TaskDescription_taskId_get(swigCPtr, this);
  }

  public void setSlaveId(String value) {
    mesosJNI.TaskDescription_slaveId_set(swigCPtr, this, value);
  }

  public String getSlaveId() {
    return mesosJNI.TaskDescription_slaveId_get(swigCPtr, this);
  }

  public void setName(String value) {
    mesosJNI.TaskDescription_name_set(swigCPtr, this, value);
  }

  public String getName() {
    return mesosJNI.TaskDescription_name_get(swigCPtr, this);
  }

  public void setParams(java.util.Map<String, String> value) {
    mesosJNI.TaskDescription_params_set(swigCPtr, this, value);
  }

  public java.util.Map<String, String> getParams() {
    return mesosJNI.TaskDescription_params_get(swigCPtr, this);
  }

  public void setArg(byte[] value) {
    mesosJNI.TaskDescription_arg_set(swigCPtr, this, value);
  }

  public byte[] getArg() { 
    return mesosJNI.TaskDescription_arg_get(swigCPtr, this); 
  }

}
