/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package mesos;

public enum TaskState {
  TASK_STARTING,
  TASK_RUNNING,
  TASK_FINISHED,
  TASK_FAILED,
  TASK_KILLED,
  TASK_LOST;

  public final int swigValue() {
    return swigValue;
  }

  public static TaskState swigToEnum(int swigValue) {
    TaskState[] swigValues = TaskState.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (TaskState swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + TaskState.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private TaskState() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private TaskState(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private TaskState(TaskState swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

